/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyStencilComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMyStencilComponentElement extends Components.MyStencilComponent, HTMLStencilElement {
    }
    var HTMLMyStencilComponentElement: {
        prototype: HTMLMyStencilComponentElement;
        new (): HTMLMyStencilComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-stencil-component": HTMLMyStencilComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyStencilComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-stencil-component": MyStencilComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-stencil-component": LocalJSX.MyStencilComponent & JSXBase.HTMLAttributes<HTMLMyStencilComponentElement>;
        }
    }
}
